# Generated by Django 4.2.1 on 2023-05-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_vacjson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vac_id", models.IntegerField()),
                ("desc", models.TextField()),
                ("skills", models.TextField()),
                ("area", models.IntegerField()),
                ("spec", models.IntegerField()),
            ],
        ),
    ]
