# Generated by Django 4.2.1 on 2023-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="area",
            field=models.CharField(
                choices=[("1", "Москва"), ("2", "Санкт-Петербург"), ("3", "Казань")],
                default="Москва",
                max_length=255,
            ),
        ),
    ]
