# Generated by Django 4.2.1 on 2023-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_resume_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vac_id", models.IntegerField()),
                ("desc", models.TextField()),
                ("skills", models.TextField()),
                ("area", models.IntegerField()),
                ("spec", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="resume",
            name="area",
            field=models.CharField(
                choices=[("1", "Москва"), ("2", "Санкт-Петербург"), ("88", "Казань")],
                default="Москва",
                max_length=255,
            ),
        ),
    ]
