# Generated by Django 4.2.1 on 2023-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_recvacancy_alter_resume_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="recvacancy", name="title", field=models.TextField(default=""),
        ),
    ]
