# Generated by Django 4.2.1 on 2023-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_recvacancy_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="recvacancy", name="area",),
        migrations.RemoveField(model_name="recvacancy", name="skills",),
        migrations.RemoveField(model_name="recvacancy", name="spec",),
        migrations.AddField(
            model_name="recvacancy", name="url", field=models.TextField(default=""),
        ),
    ]
