# Generated by Django 4.2.1 on 2023-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_recvacancy_area_remove_recvacancy_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancies", name="url", field=models.TextField(default=""),
        ),
    ]
