# Generated by Django 4.2.1 on 2023-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_vacancies_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagJsonSJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="VacJsonSJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vac_id", models.IntegerField()),
                ("file", models.JSONField()),
            ],
        ),
    ]
