# Generated by Django 4.2.1 on 2023-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_pagjsonsj_vacjsonsj"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancies", name="website", field=models.TextField(default=""),
        ),
    ]
